[global]
gravity = 9.848

[calibration]
passby = false
accel_matrix = [
    [
    1.001901595837556,
    0.0,
    0.0,
],
    [
    0.0,
    0.999519460725826,
    0.0,
],
    [
    0.0,
    0.0,
    1.0006785714285746,
],
]
gyro_matrix = [
    [
    1.0,
    0.0,
    0.0,
],
    [
    0.0,
    1.0,
    0.0,
],
    [
    0.0,
    0.0,
    1.0,
],
]

[calibration.accel_bias]
x = 0.0023925781249696243
y = -0.040075683593808975
z = 0.038281249999969624

[calibration.gyro_bias]
x = 0.0
y = 0.0
z = 0.0

[filter]
passby = true
alpha = 0.9

[trajectory]
passby = false
integrator = "trapezoid"
dt_min_ms = 1
dt_max_ms = 50

[zupt]
passby = false
impl_type = "smooth_hysteresis"
gyro_thresh = 0.15
accel_thresh = 0.6
gyro_enter_thresh = 0.15
accel_enter_thresh = 0.22
gyro_exit_thresh = 0.2
accel_exit_thresh = 0.3
enter_frames = 3
exit_frames = 3
vel_decay_tau_ms = 35.0
pos_lock_tau_ms = 110.0
vel_zero_eps = 0.03
